-- Seed data for public.languages -- ISO 639-3. Loaded after every migration
-- (supabase/config.toml -> [db.seed] -> sql_paths = ["./seed.sql"]).
--
-- id                   ISO 639-3 3-letter code, lowercase. The only identifier the app
--                      stores: user_languages.language_id, saved_phrases.language_id and
--                      translation_history.language_id all hold this string.
-- iso_639_1            The 2-letter code from the same standard, or NULL when the standard
--                      has none -- normal for the smaller languages, not a data error.
--                      Unique, so two rows can never claim the same macrolanguage code.
-- english_name         Standard English name: used in code and aria labels, and as the
--                      display fallback when a native name is missing or cannot be drawn.
-- native_name          The autonym, in the language's own script. This is what the UI shows.
-- is_supported_learning true = offered in onboarding, the language picker and search filters.
--
-- The 100 most spoken and most learned languages in the world, so every screen has a
-- complete, standard-shaped set to choose from. Idempotent, and safe to re-run at any time:
-- it only ever writes these five columns, and every profile keeps pointing at its rows by id.
insert into public.languages (id, iso_639_1, english_name, native_name, is_supported_learning) values
  ('eng','en','English','English',true),
  ('cmn',null,'Mandarin Chinese','普通话',true),
  ('zho','zh','Chinese','中文',true),
  ('hin','hi','Hindi','हिन्दी',true),
  ('spa','es','Spanish','Español',true),
  ('ara','ar','Arabic','العربية',true),
  ('ben','bn','Bengali','বাংলা',true),
  ('por','pt','Portuguese','Português',true),
  ('rus','ru','Russian','Русский',true),
  ('jpn','ja','Japanese','日本語',true),
  ('deu','de','German','Deutsch',true),
  ('fra','fr','French','Français',true),
  ('urd','ur','Urdu','اردو',true),
  ('pes','fa','Persian','فارسی',true),
  ('tur','tr','Turkish','Türkçe',true),
  ('tam','ta','Tamil','தமிழ்',true),
  ('vie','vi','Vietnamese','Tiếng Việt',true),
  ('tel','te','Telugu','తెలుగు',true),
  ('mar','mr','Marathi','मराठी',true),
  ('kan','kn','Kannada','ಕನ್ನಡ',true),
  ('ind','id','Indonesian','Bahasa Indonesia',true),
  ('tha','th','Thai','ไทย',true),
  ('ukr','uk','Ukrainian','Українська',true),
  ('nld','nl','Dutch','Nederlands',true),
  ('pol','pl','Polish','Polski',true),
  ('mya','my','Burmese','မြန်မာ',true),
  ('fil',null,'Filipino','Filipino',true),
  ('ita','it','Italian','Italiano',true),
  ('ell','el','Greek','Ελληνικά',true),
  ('kor','ko','Korean','한국어',true),
  ('swh','sw','Swahili','Kiswahili',true),
  ('heb','he','Hebrew','עברית',true),
  ('ces','cs','Czech','Čeština',true),
  ('ron','ro','Romanian','Română',true),
  ('hun','hu','Hungarian','Magyar',true),
  ('dan','da','Danish','Dansk',true),
  ('fin','fi','Finnish','Suomi',true),
  ('nob',null,'Norwegian Bokmål','Norsk bokmål',true),
  ('swe','sv','Swedish','Svenska',true),
  ('slk','sk','Slovak','Slovenčina',true),
  ('slv','sl','Slovenian','Slovenščina',true),
  ('hrv','hr','Croatian','Hrvatski',true),
  ('srp','sr','Serbian','Српски',true),
  ('bos','bs','Bosnian','Bosanski',true),
  ('mkd','mk','Macedonian','Македонски',true),
  ('sqi','sq','Albanian','Shqip',true),
  ('kat','ka','Georgian','ქართული',true),
  ('hye','hy','Armenian','Հայերեն',true),
  ('aze','az','Azerbaijani','Azərbaycan dili',true),
  ('isl','is','Icelandic','Íslenska',true),
  ('mlt','mt','Maltese','Malti',true),
  ('cym','cy','Welsh','Cymraeg',true),
  ('gle','ga','Irish','Gaeilge',true),
  ('ltz','lb','Luxembourgish','Lëtzebuergesch',true),
  ('glg','gl','Galician','Galego',true),
  ('baq','eu','Basque','Euskara',true),
  ('cat','ca','Catalan','Català',true),
  ('hat','ht','Haitian Creole','Kreyòl ayisyen',true),
  ('uzn','uz','Uzbek','Oʻzbekcha',true),
  ('kaz','kk','Kazakh','Қазақша',true),
  ('tuk','tk','Turkmen','Türkmençe',true),
  ('kir','ky','Kyrgyz','Кыргызча',true),
  ('tgk','tg','Tajik','Тоҷикӣ',true),
  ('nep','ne','Nepali','नेपाली',true),
  ('sin','si','Sinhala','සිංහල',true),
  ('snd','sd','Sindhi','سنڌي',true),
  ('pus','ps','Pashto','پښتو',true),
  ('kur','ku','Kurdish','Kurdî',true),
  ('mal','ml','Malayalam','മലയാളം',true),
  ('ory','or','Odia','ଓଡ଼ିଆ',true),
  ('asm','as','Assamese','অসমীয়া',true),
  ('pan','pa','Punjabi','ਪੰਜਾਬੀ',true),
  ('guj','gu','Gujarati','ગુજરાતી',true),
  ('bod','bo','Tibetan','བོད་སྐད',true),
  ('khm','km','Khmer','ខ្មែរ',true),
  ('lao','lo','Lao','ລາວ',true),
  ('msa','ms','Malay','Bahasa Melayu',true),
  ('tgl','tl','Tagalog','Tagalog',true),
  ('ceb','ce','Cebuano','Cebuano',true),
  ('ilo','il','Ilocano','Pagsasao nga Ilokano',true),
  ('jav','jv','Javanese','Basa Jawa',true),
  ('sun','su','Sundanese','Basa Sunda',true),
  ('yue',null,'Cantonese','粵語',true),
  ('mon','mn','Mongolian','Монгол',true),
  ('amh','am','Amharic','አማርኛ',true),
  ('tir','ti','Tigrinya','ትግርኛ',true),
  ('som','so','Somali','Af-Soomaali',true),
  ('orm','om','Oromo','Afaan Oromoo',true),
  ('hau','ha','Hausa','Harshen Hausa',true),
  ('yor','yo','Yoruba','Yorùbá',true),
  ('ibo','ig','Igbo','Asụsụ Igbo',true),
  ('kin','rw','Kinyarwanda','Ikinyarwanda',true),
  ('nya','ny','Chichewa','chiCheŵa',true),
  ('sna','sn','Shona','ChiShona',true),
  ('zul','zu','Zulu','isiZulu',true),
  ('xho','xh','Xhosa','isiXhosa',true),
  ('aka','ak','Akan','Akan',true),
  ('lug','lg','Ganda','Oluganda',true),
  ('lin','ln','Lingala','Lingála',true),
  ('kon','kg','Kongo','Kikongo',true)
on conflict (id) do update
  set iso_639_1             = excluded.iso_639_1,
      english_name          = excluded.english_name,
      native_name           = excluded.native_name,
      is_supported_learning = excluded.is_supported_learning;
